/**
 * Monogatari 脚本转换工具
 * 将剧本数据转换为 Monogatari 引擎可用的 script.js 代码
 */

class MonogatariConverter {
  constructor(options = {}) {
    this.options = {
      indent: options.indent || '    ',
      lineBreak: options.lineBreak || '\n',
      ...options
    };
  }

  /**
   * 转换完整项目数据为 Monogatari 脚本
   */
  convertToScript(projectData) {
    const { characters = {}, scenes = {}, script = {}, music = {} } = projectData;
    
    const parts = [];
    
    parts.push(this.generateHeader());
    parts.push(this.generateMessages());
    parts.push(this.generateCharacters(characters));
    parts.push(this.generateScenes(scenes));
    parts.push(this.generateMusic(music));
    parts.push(this.generateScript(script));
    
    return parts.join(this.options.lineBreak);
  }

  /**
   * 生成文件头注释
   */
  generateHeader() {
    return `/* global monogatari

Generated by Story Game Generator
https://github.com/wl-developer/story-game-generator

*/`;
  }

  /**
   * 生成消息通知定义
   */
  generateMessages(messages = {}) {
    const keys = Object.keys(messages);
    if (keys.length === 0) {
      return '';
    }
    
    const content = keys.map(key => {
      const msg = messages[key];
      return `    '${key}': { title: '${msg.title}', body: '<p>${msg.body}</p>' }`;
    }).join(',' + this.options.lineBreak);
    
    return `monogatari.action ('message').messages (${this.options.lineBreak}${content}${this.options.lineBreak}
});`;
  }

  /**
   * 生成角色定义
   */
  generateCharacters(characters) {
    const keys = Object.keys(characters);
    if (keys.length === 0) {
      return '';
    }

    const content = keys.map(key => {
      const char = characters[key];
      const parts = [];
      parts.push(`name: '${char.name}'`);
      if (char.color) parts.push(`color: '${char.color}'`);
      if (char.directory) parts.push(`directory: '${char.directory}'`);
      if (char.sprites && Object.keys(char.sprites).length > 0) {
        const sprites = Object.entries(char.sprites)
          .map(([k, v]) => `${k}: '${v}'`)
          .join(', ');
        parts.push(`sprites: { ${sprites} }`);
      }
      return `    '${key}': {${this.options.lineBreak}${this.options.indent}${parts.join(',' + this.options.lineBreak)}${this.options.lineBreak}}`;
    }).join(',' + this.options.lineBreak);

    return `monogatari.characters (${this.options.lineBreak}${content}${this.options.lineBreak}
);`;
  }

  /**
   * 生成场景定义
   */
  generateScenes(scenes) {
    const keys = Object.keys(scenes);
    if (keys.length === 0) {
      return '';
    }

    const content = keys.map(key => {
      return `    '${key}': '${scenes[key]}'`;
    }).join(',' + this.options.lineBreak);

    return `monogatari.assets ('scenes', ${this.options.lineBreak}${content}${this.options.lineBreak}
);`;
  }

  /**
   * 生成音乐定义
   */
  generateMusic(music) {
    const keys = Object.keys(music);
    if (keys.length === 0) {
      return '';
    }

    const content = keys.map(key => {
      return `    '${key}': '${music[key]}'`;
    }).join(',' + this.options.lineBreak);

    return `monogatari.assets ('music', ${this.options.lineBreak}${content}${this.options.lineBreak}
);`;
  }

  /**
   * 生成脚本内容
   */
  generateScript(script) {
    const labels = Object.keys(script);
    if (labels.length === 0) {
      return '';
    }

    const content = labels.map(label => {
      const lines = script[label];
      const linesContent = lines.map(line => {
        if (typeof line === 'string') {
          return this.formatDialogueLine(line);
        } else if (typeof line === 'object') {
          return this.formatObjectLine(line);
        }
        return '';
      }).filter(Boolean).join(this.options.lineBreak + this.options.indent);
      
      return `    '${label}': [${this.options.lineBreak}${this.options.indent}${linesContent}${this.options.lineBreak}]`;
    }).join(',' + this.options.lineBreak + this.options.lineBreak);

    return `monogatari.script (${this.options.lineBreak}${content}${this.options.lineBreak}
);`;
  }

  /**
   * 格式化对话行
   */
  formatDialogueLine(line) {
    return `'${line.replace(/'/g, "\\'")}'`;
  }

  /**
   * 格式化对象行（如 Choice）
   */
  formatObjectLine(obj) {
    if (obj.Choice) {
      return this.formatChoice(obj.Choice);
    }
    if (obj.Condition) {
      return this.formatCondition(obj.Condition);
    }
    return JSON.stringify(obj);
  }

  /**
   * 格式化选择
   */
  formatChoice(choice) {
    const dialog = choice.Dialog || '';
    const options = choice;
    const optionKeys = Object.keys(options).filter(k => k !== 'Dialog');
    
    const optionsContent = optionKeys.map(key => {
      const opt = options[key];
      return `${key}: {${this.options.lineBreak}${this.options.indent}'Text': '${opt.Text || ''}',${this.options.lineBreak}${this.options.indent}'Do': '${opt.Do || ''}'${this.options.lineBreak}}`;
    }).join(',' + this.options.lineBreak + this.options.indent);

    return `{'Choice': {${this.options.lineBreak}${this.options.indent}'Dialog': '${dialog}',${this.options.lineBreak}${this.options.indent}${optionsContent}${this.options.lineBreak}}}`;
  }

  /**
   * 格式化条件
   */
  formatCondition(condition) {
    return JSON.stringify(condition);
  }
}

module.exports = { MonogatariConverter };
