"""Aggregate all baseline runs into a single Markdown comparison table.

Reads:
  - paper/evaluation/v071/baselines/single_shot_cot/<slug>.json     (BL-2)
  - paper/evaluation/v071/baselines/zero_shot/<slug>/aggregate.json (BL-1)
  - paper/evaluation/v071/ablation-by-stage.json                    (full pipeline)
  - paper/evaluation/v071/ablation-voting-baseline-fair.json        (fair per-node)

Writes:
  - paper/evaluation/v071/baselines/comparison.md
  - Also prints to stdout.

Usage:
    cd backend && uv run python scripts/baseline_comparison.py
"""

from __future__ import annotations

import json
from pathlib import Path

PAPER_EVAL = Path("/Users/leonfeng/Baiduyun/AISoul/ai-reader-internal/paper/evaluation/v071")
BASELINES = PAPER_EVAL / "baselines"

NOVELS = [("xiyouji", "Journey to the West"), ("honglou", "Dream of the Red Chamber")]


def load_json(p: Path) -> dict | None:
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def cot_row(slug: str) -> dict:
    data = load_json(BASELINES / "single_shot_cot" / f"{slug}.json") or {}
    topo = data.get("topology") or {}
    return {
        "nodes": data.get("input_locations"),
        "assignments": data.get("output_parent_assignments"),
        "avg_depth": data.get("avg_depth"),
        "max_ch": data.get("max_children"),
        "roots": data.get("computed_roots"),
        "cycle": "yes" if data.get("has_cycle") else "no",
        "missed": data.get("missed_count"),
        "halluc": data.get("hallucinated_count"),
        "parent_P": topo.get("parent_precision"),
        "chain_acc": topo.get("chain_accuracy"),
        "cost_usd": data.get("cost_usd"),
    }


def zero_shot_row(slug: str) -> dict:
    data = load_json(BASELINES / "zero_shot" / slug / "aggregate.json") or {}
    topo = data.get("topology") or {}
    chapters_loaded = data.get("chapters_loaded") or 0
    # Expected full-book chapter counts — flag partial runs
    expected = {"xiyouji": 100, "honglou": 122, "shuihu": 121, "sanguo": 120, "fengshen": 90}
    partial = chapters_loaded and chapters_loaded < expected.get(slug, 0)
    return {
        "nodes": data.get("unique_locations"),
        "assignments": data.get("parent_assignments"),
        "max_ch": data.get("max_children"),
        "roots": data.get("root_count"),
        "parent_P": topo.get("parent_precision"),
        "chain_acc": topo.get("chain_accuracy"),
        "chapters": chapters_loaded,
        "partial": partial,
        "expected_chapters": expected.get(slug, 0),
    }


def pipeline_stages(slug: str) -> dict:
    data = load_json(PAPER_EVAL / "ablation-by-stage.json") or {}
    return data.get(slug, {})


def fair_per_node(slug: str) -> dict:
    data = load_json(PAPER_EVAL / "ablation-voting-baseline-fair.json") or {}
    return data.get(slug, {}).get("fair_intersection", {})


def fmt_num(x, pct: bool = False, digits: int = 3) -> str:
    if x is None:
        return "—"
    if isinstance(x, float):
        if pct:
            return f"{x * 100:.1f}%"
        return f"{x:.{digits}f}"
    return str(x)


def render():
    out_lines: list[str] = []
    out_lines.append("# Baseline Comparison — v0.71.2")
    out_lines.append("")
    out_lines.append("Generated by `scripts/baseline_comparison.py`.")
    out_lines.append("")

    # ── Table: Structural properties (core paper table) ──
    out_lines.append("## Table 7: Structural Properties — Journey to the West + Red Chamber")
    out_lines.append("")
    out_lines.append(
        "| Novel | Method | nodes | avg_depth | max_ch | roots | valid? | parent_P | chain_acc | notes |"
    )
    out_lines.append(
        "|-------|--------|-------|-----------|--------|-------|--------|----------|-----------|-------|"
    )

    for slug, display in NOVELS:
        stages = pipeline_stages(slug)
        zs = zero_shot_row(slug)
        cot = cot_row(slug)
        imp = stages.get("import", {})
        edm = stages.get("edmonds", {})
        full = stages.get("suffix", {})

        # Raw chapter extraction (import snapshot)
        out_lines.append(
            f"| {display} | Raw chapter LLM | {imp.get('nodes', '—')} | "
            f"{fmt_num(imp.get('depth'))} | {imp.get('max_ch', '—')} | "
            f"{imp.get('roots', '—')} | ✗ | — | — | pre-pipeline snapshot |"
        )
        # Zero-shot LLM per-chapter — flag partial runs
        if zs.get("partial"):
            zs_note = f"⚠ only {zs['chapters']}/{zs['expected_chapters']} ch cached"
        elif zs.get("chapters"):
            zs_note = "no CoT, no ctx"
        else:
            zs_note = "not run yet"
        out_lines.append(
            f"| {display} | Zero-shot LLM (per-chapter) | {zs.get('nodes') or '—'} | "
            f"— | {fmt_num(zs.get('max_ch'))} | {fmt_num(zs.get('roots'))} | ✗ | "
            f"{fmt_num(zs.get('parent_P'), pct=True)} | {fmt_num(zs.get('chain_acc'), pct=True)} | "
            f"{zs_note} |"
        )
        # Single-shot LLM-CoT
        out_lines.append(
            f"| {display} | **LLM-CoT one-shot** | {cot.get('nodes', '—')} | "
            f"{fmt_num(cot.get('avg_depth'))} | {fmt_num(cot.get('max_ch'))} | "
            f"{fmt_num(cot.get('roots'))} | ✗ | {fmt_num(cot.get('parent_P'), pct=True)} | "
            f"{fmt_num(cot.get('chain_acc'), pct=True)} | "
            f"miss={cot.get('missed', '—')} halluc={cot.get('halluc', '—')} ${cot.get('cost_usd', 0):.2f} |"
        )
        # Edmonds (no priors)
        out_lines.append(
            f"| {display} | Edmonds (no priors) | {edm.get('nodes', '—')} | "
            f"{fmt_num(edm.get('depth'))} | {edm.get('max_ch', '—')} | "
            f"{edm.get('roots', '—')} | ✓ | — | — | algorithm alone |"
        )
        # Full pipeline
        out_lines.append(
            f"| {display} | **Full (Edmonds+Prior+Suffix)** | {full.get('nodes', '—')} | "
            f"{fmt_num(full.get('depth'))} | {full.get('max_ch', '—')} | "
            f"{full.get('roots', '—')} | ✓ | — | — | paper main config |"
        )

    out_lines.append("")
    out_lines.append("**Key findings:**")
    out_lines.append(
        "- **LLM-CoT does not provide structural guarantees.** Cycles are avoided by luck, not proof; max_ch varies wildly across novels (74 on Journey, 143 on Red Chamber)."
    )
    out_lines.append(
        "- **LLM-CoT loses/hallucinates nodes.** Journey: 6 missed + 10 hallucinated. Red Chamber: 1 missed + 3 hallucinated."
    )
    out_lines.append(
        "- **parent_P gap** between LLM-CoT and Full pipeline is 21 pp on Journey (78.3 % vs 99.8 %), even larger on Red Chamber."
    )

    # ── Table: Per-node overall on intersection (v0.71.2) ──
    out_lines.append("")
    out_lines.append("## Table 8 (supplement): Per-Node Overall on Intersection (fair baseline)")
    out_lines.append("")
    out_lines.append("| Novel | Voting Overall | Full Overall | Δ |")
    out_lines.append("|-------|----------------|--------------|---|")
    fair_data = load_json(PAPER_EVAL / "ablation-voting-baseline-fair.json") or {}
    for slug, display in NOVELS + [
        ("shuihu", "Water Margin"),
        ("sanguo", "Three Kingdoms"),
        ("fengshen", "Investiture of the Gods"),
    ]:
        f = fair_data.get(slug, {}).get("fair_intersection", {})
        if not f:
            continue
        v = f.get("voting", {}).get("overall")
        fl = f.get("full", {}).get("overall")
        if v is None or fl is None:
            continue
        delta = fl - v
        out_lines.append(
            f"| {display} | {fmt_num(v, digits=4)} | {fmt_num(fl, digits=4)} | "
            f"{delta:+.4f} |"
        )

    # ── Summary ──
    out_lines.append("")
    out_lines.append("## Summary for paper §3")
    out_lines.append("")
    out_lines.append(
        "On the shared node set, the full pipeline is essentially tied with greedy voting "
        "on per-node Overall (Table 8). The value add is structural (Table 7): Edmonds "
        "*guarantees* acyclicity and single-rootedness, LLM-CoT does not, and LLM-CoT "
        "additionally corrupts the node set via missed / hallucinated entries."
    )

    # Write + print
    out_path = BASELINES / "comparison.md"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(out_lines))
    print("\n".join(out_lines))
    print(f"\n\n[saved to {out_path}]")


if __name__ == "__main__":
    render()
