"""Convert phase1_bible.json → AI Reader gold standard format.

Output matches the schema in `tests/fixtures/golden_standard_*.json` so
the existing evaluation harness (topology_metrics.compute_topology_metrics)
can run without modification.

Usage:
    uv run python scripts/bible_to_gold.py

Reads:
    paper/evaluation/contamination-free/novel/phase1_bible.json

Writes:
    paper/evaluation/contamination-free/novel/gold_standard.json
    paper/evaluation/contamination-free/novel/gold_characters.json
    paper/evaluation/contamination-free/novel/gold_relations.json
"""

from __future__ import annotations

import json
from pathlib import Path

BASE = Path(
    "/Users/leonfeng/Baiduyun/AISoul/ai-reader-internal/paper/evaluation/contamination-free/novel"
)


def main():
    bible_path = BASE / "phase1_bible.json"
    if not bible_path.exists():
        raise SystemExit(f"ERROR: {bible_path} not found — run Phase 1 first")
    bible = json.loads(bible_path.read_text())

    # ── Locations → golden_standard format ──
    locations_gold = {
        "_meta": {
            "novel": bible.get("novel_title", "Synthetic"),
            "author": "DeepSeek V3 (synthetic for contamination-free eval)",
            "version": "1.0",
            "annotation_rules": [
                "Synthetic novel generated by DeepSeek V3; ground truth = Phase 1 world bible",
                "parent_system 字段直接来自 bible.locations[].parent",
                "tier 字段直接来自 bible.locations[].tier",
            ],
            "total_locations": len(bible.get("locations") or []),
        },
        "locations": [
            {
                "name": L["name"],
                "correct_parent": L.get("parent"),
                "tier": L.get("tier"),
            }
            for L in bible.get("locations") or []
            if L.get("name")
        ],
    }

    # ── Characters → alias/canonical gold ──
    chars_gold = {
        "_meta": {
            "novel": bible.get("novel_title", "Synthetic"),
            "version": "1.0",
            "note": "Every canonical_name listed here is a valid character; every alias resolves to its canonical_name",
            "total_characters": len(bible.get("characters") or []),
        },
        "characters": [
            {
                "canonical_name": c["canonical_name"],
                "aliases": c.get("aliases") or [],
                "role": c.get("role"),
                "is_valid_character": True,
            }
            for c in bible.get("characters") or []
            if c.get("canonical_name")
        ],
    }

    # ── Relations gold ──
    rels_gold = {
        "_meta": {
            "novel": bible.get("novel_title", "Synthetic"),
            "version": "1.0",
            "categories": ["family", "intimate", "hierarchical", "social", "hostile", "other"],
            "total_relations": len(bible.get("relationships") or []),
        },
        "relations": [
            {
                "person_a": r["person_a"],
                "person_b": r["person_b"],
                "correct_type": r.get("type"),
                "correct_category": r.get("category"),
            }
            for r in bible.get("relationships") or []
            if r.get("person_a") and r.get("person_b")
        ],
    }

    out_locs = BASE / "gold_standard.json"
    out_chars = BASE / "gold_characters.json"
    out_rels = BASE / "gold_relations.json"

    out_locs.write_text(json.dumps(locations_gold, ensure_ascii=False, indent=2))
    out_chars.write_text(json.dumps(chars_gold, ensure_ascii=False, indent=2))
    out_rels.write_text(json.dumps(rels_gold, ensure_ascii=False, indent=2))

    print(f"Locations gold: {out_locs} ({len(locations_gold['locations'])} entries)")
    print(f"Characters gold: {out_chars} ({len(chars_gold['characters'])} entries)")
    print(f"Relations gold: {out_rels} ({len(rels_gold['relations'])} entries)")

    # Quick distribution sanity
    from collections import Counter

    tiers = Counter(L.get("tier") for L in locations_gold["locations"])
    cats = Counter(r.get("correct_category") for r in rels_gold["relations"])
    print(f"\nTier distribution: {dict(tiers)}")
    print(f"Category distribution: {dict(cats)}")


if __name__ == "__main__":
    main()
